### PR TITLE
Refactor RandomTips to load tips only when actually showing them

### PR DESCRIPTION
**Pull request by daaAd1**

### CODE REVIEW

**Comment by daaAd1** [comment]
Hi, 
I have looked through this again and I don't think I have done it correctly. Before refactor tips have been loaded in popup/qrdcode.js and options/options.js files. Loading tips in RandomTips.js as I have done it initially is not correct and kinda defeats the purpose of this repository.
So I have changed the way it works as shown [here](https://github.com/rugk/offline-qr-code/pull/221/files).

You are right, I haven't looked at unit tests before and they will certainly have to be changed. Unfortunately I couldn't get randomTips.test.js unit tests to start working. Running server and opening index.html from tests directory is not showing and I am getting error in console that this `TestHelper/HtmlMock.js` is not found.

**Comment by rugk** [comment]
See https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#tests for how to run tests. Basically, you need to load the add-on. Also you maybe need to setup/create the `data` files.

As for the other things, I don't know how useful this all is, given that the `import` statement of course already loads the data.
On the other hand, it probably does not hurt… :thinking:

**Comment by daaAd1** [comment]
Other option could be conditional import, something like this:
```javascript
  const shouldShowTip = RandomTips.showRandomTipIfWanted();  
  if (shouldShowTip) {
    const tips = require("/common/modules/data/Tips.js");
    RandomTips.showRandomTip(tips);
  }
```

**Comment by rugk** [comment]
> conditional import

Yeah, but this is only supported since Firefox 67: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Browser_compatibility

**Comment by daaAd1** [comment]
Ok, since that option is not supported, I do not see any other way to not import it in option.js and qrcode.js files. Should I continue by changing tests for the change I made or should I close this?

**Comment by rugk** [comment]
Well… IMHO this change is fine.

We loose the ability to load the tip data from somewhere else, adjust or inject them from the outside, but this is fine IMHO, as the tip module has enough flexibility.

But ahh, I just see why I did this: These actually _are_ the tests. Because there you need to inject the tips module.

**Comment by daaAd1** [comment]
> These actually are the tests

I am not sure what are you talking about here. Could you please clarify? Thank you

So change itself is ok now and I can proceed with changing tests?

**Comment by rugk** [comment]
You _can_ try to change these tests, but I see this will fail, because the tips module is now statically imported, and the tests depend on different values at runtime, actually… :thinking:

**Comment by rugk** [comment]
I've decided to now go the way of updating this code to use the real [lazy-loading via dynamic ES6 modules manetioned earlier](https://github.com/TinyWebEx/RandomTips/pull/4#issuecomment-540974595) in PR https://github.com/TinyWebEx/RandomTips/pull/5.

As such, I unfortunately have to close this PR. Anyway very thanks for your contribution! 😃

**Pull request closed without merging**
